# Simple convolutional NN based classifier of MRI scans - trained on Google's Teachable Machine

# Import libraries
import streamlit as st
from PIL import Image, ImageOps
# Set up the basic md for the webpage that will be generated by streamlit
st.title("Image Classification with Google's Teachable Machine")
st.header("Brain Tumor MRI Classification Example")
st.text("Upload a brain MRI Image for image classification as tumor or no-tumor")
st.text("Download test images here: https://github.com/rupindeeplearning/MRI_Classifier/brain_tumor_dataset")

from teachable_machine_classification import teachable_machine_classification

# Import the image to be classified:
uploaded_file = st.file_uploader("Choose a brain MRI ...", type="jpg")
if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption='Uploaded MRI.', use_column_width=True)
    st.write("")
    st.write("Classifying...")
    # Call the trained CNN based model to classify the image
    label = teachable_machine_classification(image,'brain_tumor_classification.h5')
    if label == 0:
        st.write("The MRI scan is healthy")
    else:
        st.write("The MRI scan has a brain tumor")

  
